language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mysql -e 'create database IF NOT EXISTS yiitest;';
  - psql -U postgres -c 'drop database if exists yiitest;'; 
  - psql -U postgres -c 'create database yiitest;';
script: phpunit