language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS yiitest;'; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'drop database if exists yiitest;'; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database yiitest;'; fi"
script: phpunit