language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

services:
  - redis-server
  - memcached
  - elasticsearch
  - mongodb

# try running against postgres 9.3
addons:
  postgresql: "9.3"

install:
  - composer self-update && composer --version
# core framework:
  - composer install --prefer-dist
  - tests/unit/data/travis/mongodb-setup.sh
  - tests/unit/data/travis/apc-setup.sh
  - tests/unit/data/travis/memcache-setup.sh
  - tests/unit/data/travis/cubrid-setup.sh
# basic and advanced application:
  - tests/unit/data/travis/setup-apps.sh

before_script:
  - echo 'elasticsearch version ' && curl http://localhost:9200/
  - mysql -e 'CREATE DATABASE yiitest;';
  - psql -U postgres -c 'CREATE DATABASE yiitest;';
  - tests/unit/data/travis/sphinx-setup.sh
  - mongo yii2test --eval 'db.addUser("travis", "test");'
# basic and advanced application:
  - tests/unit/data/travis/init-apps.sh

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover --exclude-group mssql,oci,wincache,xcache,zenddata
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "skipping application tests on HHVM"
    else
      cd apps/basic/tests && php ../vendor/bin/codecept run
      cd ../../advanced/tests && ../vendor/bin/codecept run
    fi

after_script:
  - cd ../../..
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
