#
# Travis Setup
#

# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
sudo: false

# build only on master branches
# commented as this prevents people from running builds on their forks:
# https://github.com/yiisoft/yii2/commit/bd87be990fa238c6d5e326d0a171f38d02dc253a
#branches:
#  only:
#    - master
#    - 2.1


#
# Test Matrix
#

language: php

php:
  - 7.1
  - nightly

matrix:
  fast_finish: true
  include:
    # have a separate branch for javascript tests
    - language: node_js
      node_js: 6
      dist: trusty
      # overwrite php related settings
      php:
      services:
      addons:
      install:
        - travis_retry npm install
        # disable xdebug for performance in composer
        - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
        - travis_retry composer self-update && composer --version
        - travis_retry composer install --prefer-dist --no-interaction
      before_script:
        - node --version
        - npm --version
        - php --version
        - composer --version
      script: npm test
      after_script:

  allow_failures:
    - php: nightly


services:
  - memcached
  - mysql
  - postgresql

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

# try running against postgres 9.3
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 2935307212620b0e2228ab67eadd92c9f5501ddb60549d0d86007a354d56915b

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # core framework:
  - travis_retry composer install --prefer-dist --no-interaction
  - tests/data/travis/apc-setup.sh
  - tests/data/travis/memcache-setup.sh
  - tests/data/travis/imagick-setup.sh

before_script:
  # show some versions and env information
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version
  - psql --version

  # initialize databases
  - travis_retry mysql -e 'CREATE DATABASE `yiitest`;';
  - mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED WITH mysql_native_password;";
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;";
  - psql -U postgres -c 'CREATE DATABASE yiitest;';

  # enable code coverage
  - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"

script:
  # ensure no files contain UTF-8 byte order mark
  - if ! grep -rlI $'\xEF\xBB\xBF' framework/ ; then echo "no utf8 BOM found"; else echo "found utf8 BOM in some files. See above."; exit 1; fi
  # validate composer.json
  - composer validate --no-check-lock
  - cd framework && composer validate --no-check-lock && cd ..
  # run PHPUnit
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group mssql,oci,wincache,xcache,zenddata,cubrid

after_script:
  - |
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
